-- =====================================================
-- VERIFICAR QUÉ BROKERS DEL CSV EXISTEN EN LA BD
-- =====================================================
-- Estos son los 67 emails REALES del archivo TODA.csv

WITH emails_del_csv AS (
  SELECT unnest(ARRAY[
    'amariar23@gmail.com',
    'asermusa@yahoo.com',
    'asurimnafis86@hotmail.com',
    'carlosfoot777@yahoo.com',
    'castillocvmark@gmail.com',
    'contacto@lideresenseguros.com',
    'coraliaseguros@yahoo.es',
    'cpereag04@gmail.com',
    'denisesaldana23@gmail.com',
    'dicsaa72@gmail.com',
    'didimosamudio@lideresenseguros.com',
    'eascanio@avenirgroupla.com',
    'ediskatherine@hotmail.com',
    'elenacalis@hotmail.com',
    'elizabetarce26@gmail.com',
    'fernandez_jose_08@hotmail.com',
    'gehcseguros@gmail.com',
    'genivanightingale@gmail.com',
    'georginalperez@yahoo.com',
    'herickagonzalez@lideresenseguros.com',
    'herminio.arcia@gmail.com',
    'ingridhim@hotmail.com',
    'iriamgp@hotmail.com',
    'itzygarciadeparedes@hotmail.com',
    'javiersamudio@lideresenseguros.com',
    'jazminkmilo@gmail.com',
    'josep1219@gmail.com',
    'katberguido08@gmail.com',
    'kathrin.aguirre@hotmail.com',
    'ketzaseguros@gmail.com',
    'kgonzalezseguros@gmail.com',
    'kips020969@hotmail.com',
    'kvseguros13@gmail.com',
    'lbranca68@yahoo.com',
    'lha04@live.com',
    'lissett.vergara17@gmail.com',
    'luciaydanna@gmail.com',
    'luisquiros@lideresenseguros.com',
    'luzgraciela@yahoo.com',
    'luztam2110@gmail.com',
    'marguezpty@gmail.com',
    'maria.urgelles@gmail.com',
    'maritzalezcanog@gmail.com',
    'marlynbotello@hotmail.com',
    'mhseguros84@hotmail.com',
    'minismei@hotmail.com',
    'mitxel2086@hotmail.com',
    'pauli88@yahoo.com',
    'pmontanez.01@gmail.com',
    'raul.roblesasesordeseguros@gmail.com',
    'rj.jimenez.173@gmail.com',
    'ruthmejia@cableonda.net',
    'samudiosegurospa@outlook.com',
    'sebastiana4562@hotmail.com',
    'seguros.ifranco@gmail.com',
    'seguroscontablesdac@gmail.com',
    'segurosrv@gmail.com',
    'segurosyania@gmail.com',
    'somarribaeisy@gmail.com',
    'soniaa0154@outlook.com',
    'stephyelain1416@gmail.com',
    'stheysi1725@gmail.com',
    'sujeysamudio@gmail.com',
    'tedescovicente@aol.com',
    'vhenriquez@hotmail.es',
    'xeniaaguilarpty@gmail.com',
    'yanitzajustiniani@lideresenseguros.com',
    'yiraramos@lideresenseguros.com',
    'zoelevent7@gmail.com'
  ]) as email_csv
)
SELECT 
  ecsv.email_csv,
  CASE 
    WHEN p.email IS NOT NULL THEN '✅ EXISTE'
    ELSE '❌ NO EXISTE'
  END as estado,
  b.name as nombre_broker,
  b.id as broker_id,
  b.active as activo
FROM emails_del_csv ecsv
LEFT JOIN profiles p ON LOWER(p.email) = LOWER(ecsv.email_csv)
LEFT JOIN brokers b ON b.p_id = p.id
ORDER BY estado DESC, ecsv.email_csv;

-- =====================================================
-- RESUMEN: CUÁNTOS EXISTEN VS NO EXISTEN
-- =====================================================

WITH emails_del_csv AS (
  SELECT unnest(ARRAY[
    'amariar23@gmail.com',
    'asermusa@yahoo.com',
    'asurimnafis86@hotmail.com',
    'carlosfoot777@yahoo.com',
    'castillocvmark@gmail.com',
    'contacto@lideresenseguros.com',
    'coraliaseguros@yahoo.es',
    'cpereag04@gmail.com',
    'denisesaldana23@gmail.com',
    'dicsaa72@gmail.com',
    'didimosamudio@lideresenseguros.com',
    'eascanio@avenirgroupla.com',
    'ediskatherine@hotmail.com',
    'elenacalis@hotmail.com',
    'elizabetarce26@gmail.com',
    'fernandez_jose_08@hotmail.com',
    'gehcseguros@gmail.com',
    'genivanightingale@gmail.com',
    'georginalperez@yahoo.com',
    'herickagonzalez@lideresenseguros.com',
    'herminio.arcia@gmail.com',
    'ingridhim@hotmail.com',
    'iriamgp@hotmail.com',
    'itzygarciadeparedes@hotmail.com',
    'javiersamudio@lideresenseguros.com',
    'jazminkmilo@gmail.com',
    'josep1219@gmail.com',
    'katberguido08@gmail.com',
    'kathrin.aguirre@hotmail.com',
    'ketzaseguros@gmail.com',
    'kgonzalezseguros@gmail.com',
    'kips020969@hotmail.com',
    'kvseguros13@gmail.com',
    'lbranca68@yahoo.com',
    'lha04@live.com',
    'lissett.vergara17@gmail.com',
    'luciaydanna@gmail.com',
    'luisquiros@lideresenseguros.com',
    'luzgraciela@yahoo.com',
    'luztam2110@gmail.com',
    'marguezpty@gmail.com',
    'maria.urgelles@gmail.com',
    'maritzalezcanog@gmail.com',
    'marlynbotello@hotmail.com',
    'mhseguros84@hotmail.com',
    'minismei@hotmail.com',
    'mitxel2086@hotmail.com',
    'pauli88@yahoo.com',
    'pmontanez.01@gmail.com',
    'raul.roblesasesordeseguros@gmail.com',
    'rj.jimenez.173@gmail.com',
    'ruthmejia@cableonda.net',
    'samudiosegurospa@outlook.com',
    'sebastiana4562@hotmail.com',
    'seguros.ifranco@gmail.com',
    'seguroscontablesdac@gmail.com',
    'segurosrv@gmail.com',
    'segurosyania@gmail.com',
    'somarribaeisy@gmail.com',
    'soniaa0154@outlook.com',
    'stephyelain1416@gmail.com',
    'stheysi1725@gmail.com',
    'sujeysamudio@gmail.com',
    'tedescovicente@aol.com',
    'vhenriquez@hotmail.es',
    'xeniaaguilarpty@gmail.com',
    'yanitzajustiniani@lideresenseguros.com',
    'yiraramos@lideresenseguros.com',
    'zoelevent7@gmail.com'
  ]) as email_csv
)
SELECT 
  COUNT(*) as total_emails_en_csv,
  COUNT(p.email) as existen_en_bd,
  COUNT(*) - COUNT(p.email) as faltan_crear
FROM emails_del_csv ecsv
LEFT JOIN profiles p ON LOWER(p.email) = LOWER(ecsv.email_csv);

-- =====================================================
-- LISTA DE BROKERS QUE NECESITAS CREAR
-- =====================================================

WITH emails_del_csv AS (
  SELECT unnest(ARRAY[
    'amariar23@gmail.com',
    'asermusa@yahoo.com',
    'asurimnafis86@hotmail.com',
    'carlosfoot777@yahoo.com',
    'castillocvmark@gmail.com',
    'contacto@lideresenseguros.com',
    'coraliaseguros@yahoo.es',
    'cpereag04@gmail.com',
    'denisesaldana23@gmail.com',
    'dicsaa72@gmail.com',
    'didimosamudio@lideresenseguros.com',
    'eascanio@avenirgroupla.com',
    'ediskatherine@hotmail.com',
    'elenacalis@hotmail.com',
    'elizabetarce26@gmail.com',
    'fernandez_jose_08@hotmail.com',
    'gehcseguros@gmail.com',
    'genivanightingale@gmail.com',
    'georginalperez@yahoo.com',
    'herickagonzalez@lideresenseguros.com',
    'herminio.arcia@gmail.com',
    'ingridhim@hotmail.com',
    'iriamgp@hotmail.com',
    'itzygarciadeparedes@hotmail.com',
    'javiersamudio@lideresenseguros.com',
    'jazminkmilo@gmail.com',
    'josep1219@gmail.com',
    'katberguido08@gmail.com',
    'kathrin.aguirre@hotmail.com',
    'ketzaseguros@gmail.com',
    'kgonzalezseguros@gmail.com',
    'kips020969@hotmail.com',
    'kvseguros13@gmail.com',
    'lbranca68@yahoo.com',
    'lha04@live.com',
    'lissett.vergara17@gmail.com',
    'luciaydanna@gmail.com',
    'luisquiros@lideresenseguros.com',
    'luzgraciela@yahoo.com',
    'luztam2110@gmail.com',
    'marguezpty@gmail.com',
    'maria.urgelles@gmail.com',
    'maritzalezcanog@gmail.com',
    'marlynbotello@hotmail.com',
    'mhseguros84@hotmail.com',
    'minismei@hotmail.com',
    'mitxel2086@hotmail.com',
    'pauli88@yahoo.com',
    'pmontanez.01@gmail.com',
    'raul.roblesasesordeseguros@gmail.com',
    'rj.jimenez.173@gmail.com',
    'ruthmejia@cableonda.net',
    'samudiosegurospa@outlook.com',
    'sebastiana4562@hotmail.com',
    'seguros.ifranco@gmail.com',
    'seguroscontablesdac@gmail.com',
    'segurosrv@gmail.com',
    'segurosyania@gmail.com',
    'somarribaeisy@gmail.com',
    'soniaa0154@outlook.com',
    'stephyelain1416@gmail.com',
    'stheysi1725@gmail.com',
    'sujeysamudio@gmail.com',
    'tedescovicente@aol.com',
    'vhenriquez@hotmail.es',
    'xeniaaguilarpty@gmail.com',
    'yanitzajustiniani@lideresenseguros.com',
    'yiraramos@lideresenseguros.com',
    'zoelevent7@gmail.com'
  ]) as email_csv
)
SELECT 
  ecsv.email_csv as email_faltante,
  '-- Crear este broker en el sistema' as accion
FROM emails_del_csv ecsv
LEFT JOIN profiles p ON LOWER(p.email) = LOWER(ecsv.email_csv)
WHERE p.email IS NULL
ORDER BY ecsv.email_csv;
